// Resend email provider — replaces Mailgun as the outbound email path.
//
// OWNER LAW (2026-08-14): Email = Resend. Mailgun stays in the tree for
// inbound webhook signing only; do not route new outbound email through it.
//
// Same contract as mailgun.mjs: no DB, no compliance re-check, never throw,
// body sent exactly as approved. Env only — never hardcode the key.
//
//   RESEND_API_KEY   API key (re_…)
//   RESEND_FROM      From header, e.g. "Fundhub <noreply@fundhub.ai>"
//                    Owner law: brand is Fundhub — never FundHub in From.
//                    Free-tier onboarding may use onboarding@resend.dev until
//                    the real domain is verified (SPF/DKIM).
//   RESEND_BASE_URL  optional; defaults to https://api.resend.com

import { readFile } from "node:fs/promises";
import { postJson, classify, success, failure, rejection, redact } from "./http.mjs";
import { resolveMessageAsset } from "../assets.mjs";

/** Must equal the `provider` value in message_channel_routing. */
export const PROVIDER = "resend";

export const CHANNELS = new Set(["email"]);

export const ADDRESS_FIELD = "email";

/** True once migration 164 seeds email → resend. */
export const ENABLED = true;

export const TRANSMITS = true;

const DEFAULT_BASE_URL = "https://api.resend.com";

/** Cap after sanitize — Resend/OS path limits; a multi-KB name is abuse. */
const MAX_ATTACHMENT_NAME = 180;

/**
 * Safe PDF filename only. Strips path traversal (`../`, absolute paths),
 * forces a `.pdf` extension, and caps length. Never invents pack.pdf for junk.
 * Applied to inline-generated attachments; a named registry asset already
 * carries a trusted filename from src/messaging/assets.mjs and is left as-is.
 */
function safePdfFilename(name) {
  let base = String(name ?? "letter.pdf").replace(/\\/g, "/").split("/").pop() || "letter.pdf";
  base = base.replace(/[^\w.\- ()[\]]+/g, "_").replace(/^\.+/, "");
  if (!base) base = "letter.pdf";
  if (!/\.pdf$/i.test(base)) {
    base = `${base.replace(/\.[^.]+$/, "") || "letter"}.pdf`;
  }
  if (base.length > MAX_ATTACHMENT_NAME) {
    base = `${base.slice(0, MAX_ATTACHMENT_NAME - 4)}.pdf`;
  }
  return base;
}

/**
 * Inline attachment bytes (Buffer, a base64 string, or a utf8 string when
 * `encoding: "utf8"` is set) → base64, or null. Missing/empty/whitespace/
 * not-actually-a-PDF → null. Must not throw. Must not ship a 0-byte or fake
 * PDF — validated by real magic bytes, never trusted from the caller alone.
 */
function asPdfBase64(content, encoding) {
  let b64 = null;
  if (Buffer.isBuffer(content)) {
    if (!content.length) return null;
    b64 = content.toString("base64");
  } else if (typeof content === "string") {
    const trimmed = content.trim();
    if (!trimmed) return null;
    b64 = encoding === "utf8" ? Buffer.from(trimmed, "utf8").toString("base64") : trimmed.replace(/\s+/g, "");
  } else {
    return null;
  }
  let bytes;
  try {
    bytes = Buffer.from(b64, "base64");
  } catch {
    return null;
  }
  if (!bytes.length) return null;
  if (bytes.toString("latin1", 0, 4) !== "%PDF") return null;
  return b64;
}

/** Rough plain-text fallback when the template body is HTML (multipart text part). */
function htmlToText(html) {
  return String(html)
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<\/(div|tr|h[1-6]|li)>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, "'")
    .replace(/&#39;/gi, "'")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Two attachment shapes coexist on messages.attachments (165_messages_attachments.sql
 * + 169_message_attachments.sql — see the migration note on 169):
 *
 *   - Named registry assets:  { asset|key, filename? }
 *     Resolved from src/messaging/assets.mjs; bytes are never stored in the DB.
 *   - Inline generated bytes: { filename, content|contentBase64, encoding? }
 *     Used for real-time-generated PDFs (letter/report attachments) — the
 *     caller passes the bytes directly, nothing to resolve.
 *
 * Both may appear in the same array. A missing NAMED asset is a configuration
 * bug (a template promised a file that was never registered) and is surfaced
 * as a hard error so it gets noticed. Malformed/empty/non-PDF INLINE bytes are
 * dropped, never faked — one bad generated file must not block the send.
 */
async function loadAttachments(list) {
  if (list == null || list === "") return { files: [], error: null };
  if (typeof list === "string") {
    try { list = JSON.parse(list); } catch { return { files: [], error: null }; }
  }
  if (!Array.isArray(list) || list.length === 0) return { files: [], error: null };
  const files = [];
  for (const item of list) {
    if (!item || typeof item !== "object") continue;

    const inline = item.contentBase64 ?? item.content;
    if (inline != null) {
      const content = asPdfBase64(inline, item.encoding);
      if (!content) continue; // malformed/empty/non-PDF — dropped, never faked
      const file = { filename: safePdfFilename(item.filename), content };
      // Only set when the caller actually said — Resend's shape today is bare
      // { filename, content }, and inventing a content_type nobody asked for
      // is not this function's call to make.
      const contentType = item.contentType || item.content_type;
      if (contentType) file.content_type = contentType;
      files.push(file);
      continue;
    }

    const key = item.asset || item.key;
    if (key == null) continue; // no bytes and no named asset — nothing to attach, drop

    const asset = resolveMessageAsset(key);
    if (!asset) {
      return { files: [], error: `unknown attachment asset: ${String(key || "")}` };
    }
    try {
      const bytes = await readFile(asset.absPath);
      files.push({
        filename: item.filename || asset.filename,
        content: bytes.toString("base64"),
        content_type: asset.contentType
      });
    } catch (err) {
      return {
        files: [],
        error: `could not read attachment ${asset.filename}: ${String(err && err.message || err)}`
      };
    }
  }
  return { files, error: null };
}

function config(env) {
  const apiKey = env.RESEND_API_KEY;
  const from = env.RESEND_FROM;
  const missing = [
    !apiKey && "RESEND_API_KEY",
    !from && "RESEND_FROM"
  ].filter(Boolean);
  if (missing.length) return { ok: false, missing };
  return {
    ok: true,
    apiKey,
    from,
    baseUrl: String(env.RESEND_BASE_URL || DEFAULT_BASE_URL).replace(/\/+$/, "")
  };
}

export async function send(message = {}, options = {}) {
  try {
    return await attempt(message, options);
  } catch (err) {
    return failure(`resend provider error: ${String((err && err.message) || err)}`);
  }
}

async function attempt(message, { fetchImpl, timeoutMs, signal, env = process.env } = {}) {
  const cfg = config(env);
  if (!cfg.ok) {
    return failure(`resend is not configured: ${cfg.missing.join(", ")} not set`);
  }

  const to = String(message.to || "").trim();
  if (!to) return rejection("no destination email address on the message");

  const body = String(message.body ?? "");
  if (!body) return rejection("message body is empty");

  const looksHtml = /<!DOCTYPE\s+html|<html[\s>]|<table[\s>]/i.test(body);
  const payload = {
    from: cfg.from,
    to: [to],
    subject: message.subject ? String(message.subject) : "(no subject)"
  };
  if (looksHtml) {
    payload.html = body;
    payload.text = htmlToText(body);
  } else {
    payload.text = body;
  }
  if (message.providerRef) {
    payload.headers = { "X-Fundhub-Ref": String(message.providerRef) };
  }
  const attached = await loadAttachments(message.attachments);
  if (attached.error) return rejection(attached.error);
  if (attached.files.length) payload.attachments = attached.files;

  const res = await postJson(`${cfg.baseUrl}/emails`, {
    headers: {
      Authorization: `Bearer ${cfg.apiKey}`,
      Accept: "application/json"
    },
    body: JSON.stringify(payload),
    contentType: "application/json",
    timeoutMs,
    fetchImpl,
    signal,
    env,
    what: "resend email"
  });

  if (res.status === 0) return failure(res.error || "resend request failed");

  const verdict = classify(res.status);
  if (verdict.status === "rejected") {
    return rejection(res.error || `resend rejected the message (HTTP ${res.status})`);
  }
  if (verdict.status === "failed") {
    return failure(res.error || `resend returned HTTP ${res.status}`, { retryable: true });
  }

  const providerMessageId = res.body && typeof res.body.id === "string" ? res.body.id : null;
  if (!providerMessageId) {
    return failure(redact(`resend accepted the message but returned no id (HTTP ${res.status})`));
  }
  return success(providerMessageId);
}

export default send;
